Configure network policies
cloudogu/k8s-service-discovery pull request #71
Opened 2024-12-10 12:27 UTC by nhinze23

Resolves #69

2024-12-10 13:05 UTC, nroeske requested changes
The go version in the Jenkinsfile must be upgraded to 1.23.4

2024-12-10 13:05 UTC, nroeske commented on controllers/interfaces.go
> +type doguInterace interface {
```suggestion
type doguInterface interface {
```

2024-12-12 06:57 UTC, nhinze23 commented on controllers/expose/ingressClassCreator_test.go
> +	selfDeployment := &v1.Deployment{ObjectMeta: metav1.ObjectMeta{Name: "k8s-service-discovery-controller-manager", Namespace: namespace}}
I created the const var but i won't use it in the test because this would not leak an accidentally change of the value.

2024-12-12 06:57 UTC, nhinze23 commented on controllers/expose/ingressUpdater.go
> +			// OwnerReferences: []v1.OwnerReference{service},
Yes ingress should be delete with a delete owner. Now the owner is the service so it will be deleted if the dogu is deleted.

2024-12-12 06:58 UTC, cesmarvin commented on controllers/interfaces.go
> +type tcpUpdServiceExposer interface {
🚫 **[checkstyle]** <unused> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>type `tcpUpdServiceExposer` is unused
<!-- __reviewdog__:ChBlNzc3ZjdmZTIwNmZhOTAxEgpjaGVja3N0eWxl -->

2024-12-12 07:08 UTC, cesmarvin commented on controllers/expose/portHandler.go
> +	if strings.ToUpper(string(servicePort.Protocol)) != strings.ToUpper(string(exposedPort.Protocol)) {
🚫 **[checkstyle]** <staticcheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>SA6005: should use strings.EqualFold instead
<!-- __reviewdog__:ChA5NGY4MTA2ODc0MTZiMGYwEgpjaGVja3N0eWxl -->

2024-12-12 07:18 UTC, cesmarvin commented on controllers/interfaces.go
> +type tcpUpdServiceExposer interface {
🚫 **[checkstyle]** <unused> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>type `tcpUpdServiceExposer` is unused
<!-- __reviewdog__:ChBkOGUyMzU5ZDAyMzJlMGExEgpjaGVja3N0eWxl -->

2024-12-12 14:32 UTC, nroeske commented on k8s/helm/templates/rbac.yaml
File is empty. Can it be deleted?

2024-12-12 14:34 UTC, nroeske commented on controllers/expose/ingressClassCreator.go
> +	namespace             string
The namespace of the structs is only used as a reference in a comment. Can the namespace be removed?

2024-12-12 14:38 UTC, nroeske commented on controllers/expose/ingressClassCreator.go
>  // isIngressClassAvailable check whether an ingress class with the given name exists in the current namespace.
Is only the namespace really checked? It seems to me that it is a cluster-wide search for IngressClasses with the name

2024-12-12 14:41 UTC, nroeske commented on main.go
>  	options := getK8sManagerOptions(watchNamespace)
Shouldn't the error be catched before we get the K8sManagerOptions? The error is thrown beforehand by reading the environment variable

2024-12-12 14:43 UTC, nroeske commented on controllers/serviceController_test.go
Maybe add a test to check if no networkPolicy is added when networkPolicies are disabled

2024-12-13 07:17 UTC, nhinze23 commented on controllers/serviceController_test.go
See test `should remove networkpolicy if disabled`

2024-12-13 07:47 UTC, nroeske approved these changes
LGTM!

2024-12-13 12:27 UTC, merged